Profilepage
DErdmann1/Quiz-App pull request #4
Opened 2023-06-02 20:09 UTC by DErdmann1

div. changes

2023-06-03 13:31 UTC, AliaksandraNovikava requested changes
I hope my comments help you improve your code =)

2023-06-03 13:31 UTC, AliaksandraNovikava commented on index.html
> +    <script src="index.js"></script>
Your `index.js` file is inside a JS folder, so you need to adjust the path like you did for your css stylesheet. Also I think it's common to have all folder names in lowercase. Furthermore you need to add `defer`.
` <script src="/js/index.js" defer></script>`

(Here you can find some information on defer-attribute: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script)

Please check your other `html` files =)

2023-06-03 13:31 UTC, AliaksandraNovikava commented on index.html
> +        </div>
I don't think you need this `<div>` element. 
You can place your bookmark icon inside you questions `<section>` and position it with `position: absolute` (and other properties like e.g. top and right, if you want to place it in you top right corner) in a place you want it to be. 

There are two ways to add `svg` or (like you tried to do so) a font awesome icon to your code:
1. You can place your `svg` inside an `<img>` tag (e.g. `<img src="/images/bookmark-solid.svg"/>`).
2. Copy the entire font-awesome directory into your project. In the `<head>` of your html, reference the location to your font-awesome.min.css. This way you can use the `<i>` tag, like you already did.

2023-06-03 13:31 UTC, AliaksandraNovikava commented on index.html
> +          </div>
You don't need anchor elements for your tags. You would use an `<a>` tag for a link.

How about replacing your `<div>` elements with an `<ul>`:
```
<ul class="your-ul-class">
   <li class="your-li-class">#html</li>
   <li class="your-li-class">#flexbox</li>
   <li class="your-li-class">#css</li>
</ul>
```

2023-06-03 13:31 UTC, AliaksandraNovikava commented on index.html
> +      <footer class="footer">
How about adding a `<nav>` element (semantic element) to your footer?

2023-06-03 13:31 UTC, AliaksandraNovikava commented on index.html
> +            /></svg
I would recommend to use a different way to place `svg` in your code. 
You can place your `svg` inside an `<img>` tag (e.g. `<img src="/images/house-solid.svg"/>`).
This way you can reduce your code by a lot =)

(I would also recommend to remove `(1)` from your `svg` name for a more cleaner code =))

2023-06-03 13:31 UTC, AliaksandraNovikava commented on profile.html
> +    <script src="index.js"></script>
Please refer to my comment on your `index.html` =)

2023-06-03 13:31 UTC, AliaksandraNovikava commented on profile.html
> +      <img src="../Quiz App/images/dogprofilepage.png" alt="Dog" />
Your image is not loading because your path is wrong.
You don't have to refer to you root directory (here /Quiz App/).
If you change the `src` to `src="/images/dogprofilepage.png"`, you will see your dog image =)

2023-06-03 13:31 UTC, AliaksandraNovikava commented on profile.html
> +    <main>
How about adding some padding to your `<main>` element so your content won't stick to your viewport border?

2023-06-03 13:31 UTC, AliaksandraNovikava commented on profile.html
> +      <footer class="footer">
Please refer to my comments on your `index.html` =)

Also you forgot to add anchor elements to create links to your other pages.

2023-06-03 13:31 UTC, AliaksandraNovikava commented on index.html
> +        <a href="" class="navicon"
Unfortunately your form page can not be accessed because you forgot to add your link's destination `href="/form.html"` in all your html files.

2023-06-03 13:31 UTC, AliaksandraNovikava commented on bookmarks.html
> +      <footer class="footer">
Please refer to my comments on your `index.html` =)

Also you forgot to add anchor elements to create links to your other pages.

2023-06-03 13:31 UTC, AliaksandraNovikava commented on form.html
> +    <footer class="footer">
Please refer to my comments on your `index.html` =)

Also you forgot to add anchor elements to create links to your other pages.

2023-06-03 13:31 UTC, AliaksandraNovikava commented on bookmarks.html
> +    <script src="index.js"></script>
Please refer to my comments on your `index.html` =)

2023-06-03 13:31 UTC, AliaksandraNovikava commented on bookmarks.html
> +        <i class="fa-solid fa-bookmark fa-constant"></i>
Please refer to my comments on your `index.html` =)

2023-06-03 13:31 UTC, AliaksandraNovikava commented on bookmarks.html
> +          </div>
Please refer to my comments on your `index.html` =)

2023-06-03 13:31 UTC, AliaksandraNovikava commented on form.html
> +    <script src="index.js"></script>
Please refer to my comments on your `index.html` =)

2023-06-03 13:31 UTC, AliaksandraNovikava commented on form.html
> +      <label for="frage">Your question:</label><br />
The value of the `for` attribute must be the same as the `id` of the element it is related to.
Here you should change your `for` value to `question`, like the `id` of your following `textarea`.

Please check your following label elements =)

(I would recommend to use english names for values.)

2023-06-03 13:31 UTC, AliaksandraNovikava commented on form.html
> +      <input type="submit" value="Senden" />
How about changing your `input` element to a `button` element with `type="submit"`?

2023-06-03 13:31 UTC, AliaksandraNovikava commented on CSS/styles.css
> +  margin-right: 10px;
I'm not sure how you want to style your tags, but how about positioning your tag-containers in the center of the parent .flex-container. 
One of the possible ways could be as follows:
You could remove everything in lines 57-60. Instead you can style you parent `.flex-container` element:
- add some padding: e.g. `padding: 10px;`
- add some gap: e.g `gap: 5px;`
- (`justify-content: flex-start;` isn't doing anything in your code)

2023-06-03 13:31 UTC, AliaksandraNovikava commented on CSS/styles.css
> +}
How about adding some space at the bottom of your `body` or `main`, so that your cards are not covered by the `footer` when you scroll to the bottom?

2023-06-04 21:02 UTC, DErdmann1 commented
Thanks a lot for your nice Review! :)

2023-06-04 21:02 UTC, closed without merging

2023-06-05 06:07 UTC, josch87 commented on index.html
> +        </div>
I would recommend using a package manager here like npm in order to use Font Awesome: https://fontawesome.com/docs/web/setup/packages

2023-06-05 06:09 UTC, josch87 commented on index.html
> +            /></svg
Placing it as an img element has some sideeffects to the svg though so I would not recommend that way in every project. You can have a look into https://www.mediaevent.de/svg-in-html-seiten/ in order to decide which method fits best to your project.